### ISSUE TITLE
Show tabbing doesn't work nicely

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/designsystem#111]
https://designsystem.gov.au/components/select/accessibility/#keyboard-accessibility

Will skip a bunch of items and then stop on the tab button itself.

In direction links it will skip the last one
https://designsystem.gov.au/components/direction-links/accessibility/#keyboard-accessibility

**Comment by alex-page** [comment]
Due to feedback we had on the widget we decided the best way to show the tabbing was to do one iteration then stop. I understand that isn't perfect however stopping focus from moving inside an iframe when an action happened outside the iframe proved to be quite challenging.

I will investigate those specific components and see if I can fix them up 👍

**Comment by dominikwilkowski** [comment]
The select component tabbing is broken because the disabled items have the `js-focus-me` class. just remove that and it's all sweet.

**Comment by dominikwilkowski** [comment]
And all components skip the last item. That would be the bug in the direction links one I mentioned above.

**Comment by alex-page** [comment]
Thanks @dominikwilkowski I'll see these get fixed.
