### ISSUE TITLE
How to use the new font-size and space functions

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#77]
Why is this better than what you had before?

- Consistency by having a predetermined list fonts
- No magic numbers like 0.852em.
- No Em issues
- Common language between Devs and Designers (px)
- Fall back for ie8 with rem for A11y
- Using the function with line-height we can have determinable heights to things.

**Comment by sukhrajghuman** [comment]
@alex-page 
https://gist.github.com/sukhrajghuman/1f8cc5b0677be84f6de617ffd26ba6fd

**Comment by alex-page** [comment]
> These are the values that are applied to the above CSS property. It is not a requirement to use unit. Other units you may use are px, %, rem or em.

`It is not a requirement` maybe say `It is recommended to use unit however it is not a requirement`

**Comment by sukhrajghuman** [comment]
@alex-page changed it up a fair bit. Lmk what you think.

**Comment by alex-page** [comment]
`The AU-space function accepts two required parameters and one optional parameter:`

I think in this sentence you should say the three parameters and then explain them below. I don't think people who are new to this will understand those titles are the parameters.

I think it would be good to make it obvious that lineheight and fontsize map are variables in the examples. I would also like a basic explanation of font size like the awesome one you did for line height.

I would move this sentence to line-height `When the line-height is a number without a unit, it is multiplied by the elements own font-size, to produce the height of the element. If we have a font-size of 16px (sm) and a line-height of 1.25 (heading), the element height would be 16px * 1.25 = 20px.`

I would then rework the `how an element height is calculated` section to be `making sure typography snaps to a grid` and start it by saying `a problem occurs when we increase the...` 

Let me know what you think, overall really good job and the screenshots with the grid are a nice touch!

**Comment by alex-page** [comment]
I still reckon being explicit helps for that parameter part. `The AU-space function accepts three parameters, the property you wish to add space to, the values of the spacing size and an ie8 pixel fallback.` Then going into the titles a user knows what to expect. I don't think people know what parameters are so this might help.

I think we can remove the part about it being a `sass-map`. I think what I was going for in my comment was that the example can show the variable name.

```
$AU-fontsize-map: (
	xs:   14,
	sm:   16,
	md:   20,
	lg:   24,
	xl:   32,
	xxl:  40,
	xxxl: 48
) !default;
```

`We are using numbers to set the line-height property` I think instead of saying what we do immediately it would be a good opportunity to explain the different ways to set a line height. Then say we use this one.

Nice work with the comments! They feel a little out of place, maybe move them above the code snippets?

**Comment by sukhrajghuman** [comment]
Thanks for going through this again man appreciate that

> I still reckon being explicit helps for that parameter part. The AU-space function accepts three parameters, the property you wish to add space to, the values of the spacing size and an ie8 pixel fallback.

I agree with these changes you suggested on the parameters part.

> I don't think people know what parameters are so this might help.

I'm super confused by who our target audience actually. If we assume they may not understand parameters, do you think I should also explain how the below sass works. 


```scss
$AU-fontsize-map: (
	xs:   14,
	sm:   16,
	md:   20,
	lg:   24,
	xl:   32,
	xxl:  40,
	xxxl: 48
) !default;
```

They might not know what `!default` is. Or even what `$AU-fontsize-map`. Just a little bit confused on the level of detail I should be going into and who the target audience is. I think we assume basic html/css/sass knowledge?

The title of the article is also "How to **use** the new font-size and space functions", so maybe that's confusing me. Because only developers will be using the functions explicitly. Should I rename the article? The level of technicality and detail seems a bit inconsistent at the moment.

**Comment by alex-page** [comment]
I would assume they don't know what `!default` is as from most implementations people don't know about it.

I think giving more context is best. I don't think we need to explain maps, I think showing the variable is enough to get somebody understanding what it is in context. Let me know what you think?

**Comment by sukhrajghuman** [comment]
>We are using numbers to set the line-height property I think instead of saying what we do immediately it would be a good opportunity to explain the different ways to set a line height. Then say we use this one.

I can do this, should I delete the following then?

>Mozilla have a great article that explains why numbers are preferred over length to set the line-height.

**Comment by alex-page** [comment]
I don't think so it's good to have a resource to back it up 👍 I think combine them.

**Comment by alex-page** [comment]
`which in most browsers is 16px.` should be `which by default is 16px.`

Suggested change:
> An optional third parameter is the pixelfallback, which is of type boolean. By default, this is set to true to support pixel fallback for Internet Explorer 8 users.` 

> `pixelfallback` is a boolean that toggles support for a pixel fallback for Internet Explorer 8 users, by default it is set to true.

Then publish this !!!
